language: go

os: linux
dist: bionic
go: 1.14.x

cache:
  directories:
    - ${HOME}/.cache/go-build
    - ${GOPATH}/pkg/mod
    - ${GOPATH}/bin

env:
  global:
    - GCR_REPO: ${HOME}/gcr

stages:
  - Build imgsync
  - Sync Kubeadm
  - Sync Flannel
  - Sync Helm
  - Sync Istio
  - Sync Distroless
  - Sync Samples
  - Sync Linkerd
  - Sync Spinnaker
  - Sync KNative

before_script:
  - bash .travis-before.sh

jobs:
  include:
    - name: Build imgsync
      stage: Build imgsync
      script:
        - make install
        - go get -u github.com/gozap/msgsend
    - name: Sync Kubeadm
      stage: Sync Kubeadm
      script:
        - imgsync gcr --kubeadm --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Flannel
      stage: Sync Flannel
      script:
        - imgsync flannel --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Helm
      stage: Sync Helm
      script:
        - imgsync gcr --namespace kubernetes-helm --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Istio
      stage: Sync Istio
      script:
        - imgsync gcr --namespace istio-release --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Distroless
      stage: Sync Distroless
      script:
        - imgsync gcr --namespace distroless --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Samples
      stage: Sync Samples
      script:
        - imgsync gcr --namespace google-samples --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Linkerd
      stage: Sync Linkerd
      script:
        - imgsync gcr --namespace linkerd-io --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync Spinnaker
      stage: Sync Spinnaker
      script:
        - imgsync gcr --namespace spinnaker-marketplace --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report
    - name: Sync KNative
      stage: Sync KNative
      script:
        - imgsync gcr --namespace knative-releases --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --process-limit 30 --manifests ${GCR_REPO}/manifests --report

after_failure:
  - bash .travis-after-failure.sh

after_success:
  - bash .travis-after-success.sh
